resolver: lts-5.13

packages:
- '.'
- location:
    git: git@github.com:bos/hdbc-mysql.git
    commit: d43ea057019ff683f278f36af410f4d3cbc731bc
- location:
    git: git@github.com:kakkun61/haskell-relational-record.git
    commit: 5174a5217e5f1b83d2db153e69e6554af721b9ae
  subdirs:
  - HDBC-session/
  - names-th/
  - persistable-record/
  - persistable-types-HDBC-pg/
  - relational-query/
  - relational-query-HDBC/
  - relational-record/
  - relational-schemas/
  - sql-words/
  - text-postgresql/

extra-deps:
#- relational-record-0.1.3.0
#- persistable-types-HDBC-pg-0.0.1.3
#- relational-query-0.8.1.0
#- relational-query-HDBC-0.6.0.0
#- HDBC-session-0.1.0.0
#- names-th-0.2.0.1
#- persistable-record-0.4.0.0
#- relational-schemas-0.1.2.2
#- sql-words-0.1.3.1
#- text-postgresql-0.0.2.0
